export interface FoodWithQuantity {
    food: string,
    quantity: number,
}

export interface CiqualData {
    // "ag_butyrique": string,
    // "ag_caproique": string,
    // "ag_caprylique": string,
    // "ag_caprique": string,
    // "ag_laurique": string,
    // "ag_myristique": string,
    // "ag_palmitique": string,
    // "ag_stearique": string,
    // "ag_oleique": string,
    // "ag_linoleique": string,
    // "ag_alpha_linolenique": string,
    // "ag_arachidonique": string,
    // "EPA": string,
    // "DHA": string,
    "agmi": string,
    "agpi": string,
    "ags": string,
    // "acides_organiques": string,
    "alcool": string,
    // "amidon": string,
    // "beta_carotene": string,
    "calcium": string,
    // "cendres": string,
    // "chlorure": string,
    "cholesterol": string,
    // "cuivre": string,
    // "eau": string,
    // "energie_jones_avec_fibres_kj": string,
    // "energie_jones_avec_fibres_kcal": string,
    // "energie_reg_ue_kj": string,
    "energie_reg_ue_kcal": string,
    "fer": string,
    "fibres": string,
    // "fructose": string,
    // "galactose": string,
    "glucides": string,
    // "glucose": string,
    // "iode": string,
    // "lactose": string,
    "lipides": string,
    // "magnesium": string,
    // "maltose": string,
    // "manganese": string,
    "phosphore": string,
    // "polyols": string,
    "potassium": string,
    "proteines": string,
    // "proteines_jones": string,
    // "retinol": string,
    // "saccharose": string,
    // "chlorure_de_sodium": string,
    "sodium": string,
    "sucres": string,
    // "selenium": string,
    // "vitamine_b1": string,
    // "vitamine_b2": string,
    // "vitamine_b3": string,
    // "vitamine_b5": string,
    // "vitamine_b6": string,
    // "vitamine_b9": string,
    // "vitamine_b12": string,
    // "vitamine_c": string,
    "vitamine_d": string,
    // "vitamine_e": string,
    // "vitamine_k1": string,
    // "vitamine_k2": string,
    // "zinc": string,
    // "alim_code": string,
    // "alim_grp_code": string,
    // "alim_grp_nom_fr": string,
    "alim_nom_fr": string,
    // "alim_nom_sci": string,
    // "alim_ssgrp_code": string,
    // "alim_ssgrp_nom_fr": string,
    // "alim_ssssgrp_code": string,
    // "alim_ssssgrp_nom_fr": string,
}

export interface FoodDataWithQuantity {
    quantity: number,
    // "ag_butyrique": string,
    // "ag_caproique": string,
    // "ag_caprylique": string,
    // "ag_caprique": string,
    // "ag_laurique": string,
    // "ag_myristique": string,
    // "ag_palmitique": string,
    // "ag_stearique": string,
    // "ag_oleique": string,
    // "ag_linoleique": string,
    // "ag_alpha_linolenique": string,
    // "ag_arachidonique": string,
    // "EPA": string,
    // "DHA": string,
    "agmi": string,
    "agpi": string,
    "ags": string,
    // "acides_organiques": string,
    "alcool": string,
    // "amidon": string,
    // "beta_carotene": string,
    "calcium": string,
    // "cendres": string,
    // "chlorure": string,
    "cholesterol": string,
    // "cuivre": string,
    // "eau": string,
    // "energie_jones_avec_fibres_kj": string,
    // "energie_jones_avec_fibres_kcal": string,
    // "energie_reg_ue_kj": string,
    "energie_reg_ue_kcal": string,
    "fer": string,
    "fibres": string,
    // "fructose": string,
    // "galactose": string,
    "glucides": string,
    // "glucose": string,
    // "iode": string,
    // "lactose": string,
    "lipides": string,
    // "magnesium": string,
    // "maltose": string,
    // "manganese": string,
    "phosphore": string,
    // "polyols": string,
    "potassium": string,
    "proteines": string,
    // "proteines_jones": string,
    // "retinol": string,
    // "saccharose": string,
    // "chlorure_de_sodium": string,
    "sodium": string,
    "sucres": string,
    // "selenium": string,
    // "vitamine_b1": string,
    // "vitamine_b2": string,
    // "vitamine_b3": string,
    // "vitamine_b5": string,
    // "vitamine_b6": string,
    // "vitamine_b9": string,
    // "vitamine_b12": string,
    // "vitamine_c": string,
    "vitamine_d": string,
    // "vitamine_e": string,
    // "vitamine_k1": string,
    // "vitamine_k2": string,
    // "zinc": string,
    // "alim_code": string,
    // "alim_grp_code": string,
    // "alim_grp_nom_fr": string,
    "alim_nom_fr": string,
    // "alim_nom_sci": string,
    // "alim_ssgrp_code": string,
    // "alim_ssgrp_nom_fr": string,
    // "alim_ssssgrp_code": string,
    // "alim_ssssgrp_nom_fr": string,
}